#!/usr/bin/env bash
#
# aursearch
#
# search and install packages from the AUR
# @author William Hleucka <william.hleucka@gmail.com>
#
#
if  [[ $# -eq 0 ]]; then
    printf "My life for Aur\n"
else
    # yay search w/ positional argument
    # sed join lines with =>
    # tr squeeze repeats of " " with single " "
    # sort the results
    # fzf list
    # cut package name from package line
    # yay install selected package
    selected=`yay -Ss $1 | sed 'N;s/\n/=>/' | tr -s ' ' | sort | fzf-tmux --header 'Select a package to install...' | cut -d " " -f1`
    yay -S $selected
fi
