#!/usr/bin/env bash


if [ $1 = "up" ]; then
  echo "Connecting..."
  #expressvpn connect 'Canada - Vancouver'
  expressvpn connect 'USA - Seattle'
  sudo systemctl restart docker.service
elif [ $1 = "down" ]; then
  echo "Disconnecting..."
  expressvpn disconnect
  sudo systemctl restart docker.service
elif [ $1 = "status" ]; then
  expressvpn status
else
  echo "Eh?"
fi
