directory: ~/Music  # Where the cleaned-up music will be stored
library: ~/.config/beets/musiclibrary.db  # Database for tracking your collection

import:
  copy: no       # Copy files to the beets library directory
  write: yes      # Write metadata to files
  move: no        # Move files instead of copying
  autotag: yes    # Automatically tag files using MusicBrainz
  timid: no       # Ask for confirmation on changes

paths:
  default: '$albumartist/$album/$track - $title'
  singleton: 'Singles/$artist - $title'
  comp: 'Compilations/$album/$track - $title'
  albumtype:soundtrack: 'Soundtracks/$album/$track - $title'

plugins:
#  - fetchart  # Download album art
  - embedart  # Embed album art into files
#  - convert   # Optional: Convert to a standard format (MP3, FLAC, etc.)
  - scrub     # Remove unnecessary metadata

fetchart:
  auto: yes
  cautious: yes  # Avoid replacing existing artwork if it's decent
  sources: coverart itunes amazon albumart google
  minwidth: 300  # Ensure artwork is at least 300x300 pixels

embedart:
  auto: yes
  maxwidth: 600  # Resize large images to fit within 600x600 pixels

id3v2:
  force: yes  # Ensure ID3v2 tagging for compatibility
